### ISSUE TITLE
Make this into a GitBook?

### ISSUE THREAD

**Issue by kennetpostigo** [kriskowal/gtor#38]
Hey I stumbled across this and wondered if you could make this into a neat little Gitbook.

**Comment by arikon** [comment]
:+1:

**Comment by kriskowal** [comment]
I can look into it and pull requests welcome.

**Comment by kennetpostigo** [comment]
@kriskowal check out https://www.gitbook.com to publish it as a GitBook. I was looking into doing it for you but it only lets me publish under my username and I don't want to take credit for your great work.
<img width="800" alt="screen shot 2015-10-06 at 8 46 54 pm" src="https://cloud.githubusercontent.com/assets/8888991/10326631/7edafb82-6c6b-11e5-9a05-486c8a04efd0.png">

**Comment by kriskowal** [comment]
Thanks for the tip. This is a thing now. https://www.gitbook.com/book/kriskowal/gtor/details

I’ll probably replace/augment the README.md with a link out to this when the content starts to diverge. Still a lot of writing to do on this topic. Maybe when I retire.

**Comment by timofonic** [comment]
Please consider it, it would make it really interesting.

Are you convinced about md? What about AsciiDoc?

**Comment by yuchi** [comment]
It has already been done AFAIK. See https://www.gitbook.com/book/kriskowal/gtor/details

**Comment by sibelius** [comment]
it is looks like this is in a legacy of gitbook https://legacy.gitbook.com/book/kriskowal/gtor/details

can we upgrade?
